### ISSUE TITLE
problem with finding '/tmp/probe_blaster' files

### ISSUE THREAD

**Issue by vguerracanedo** [strongles/ervin#27]
Dear Ervin team, 

I get the following error when I try to run the program:

==
Blasting against Genome DB: 100% (14 of 14) || Elapsed Time: 0:16:45 Time:  0:16:45
Traceback (most recent call last):
  File "/home/vguerra/ervin_env/bin/ervin", line 33, in <module>
    sys.exit(load_entry_point('ervin==0.0.6', 'console_scripts', 'ervin')())
  File "/home/vguerra/ervin_env/lib/python3.7/site-packages/ervin/ervin.py", line 66, in run
    run_ts)
  File "/home/vguerra/ervin_env/lib/python3.7/site-packages/ervin/probe_blaster.py", line 126, in run_probe_blaster
    run_time, output_dir)
  File "/home/vguerra/ervin_env/lib/python3.7/site-packages/ervin/probe_blaster.py", line 103, in print_results
    with open(output_filepath, 'w') as result_out:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/probe_blaster/POL_ALV_AJG42161.1_Pol_[Avian_leukosis_virus_ev/J]_2020-08-10_09-45-23.tsv'
Done
==

Do you guys have any suggestions of what I could do to troubleshoot the problem? 

Best, 
Vanessa

**Comment by jshleap** [comment]
Following this issue I noticed that the output_dir option is not used in your run code. For example, line 62 of the ervin.py module only has 5 arguments, while the function being called (run_probe_blaster) has 6, being the 6th one the output directory.

**Comment by vguerracanedo** [comment]
I just realized that I had the config file in the wrong location... plop!

**Comment by gargkritika** [comment]
Hi Vanessa,

Can you please elaborate on how you resolved this issue. I am having the same problem. I have the config file in the same folder from which I am running ERVin. I have also edited the folder name in which the results need to be stored. However, I still get the same error.

Thank you very much.

Best regards
Kritika

**Comment by philge** [comment]
> Dear Ervin team,
> 
> I get the following error when I try to run the program:
> 
> # ==
> Blasting against Genome DB: 100% (14 of 14) || Elapsed Time: 0:16:45 Time: 0:16:45
> Traceback (most recent call last):
> File "/home/vguerra/ervin_env/bin/ervin", line 33, in
> sys.exit(load_entry_point('ervin==0.0.6', 'console_scripts', 'ervin')())
> File "/home/vguerra/ervin_env/lib/python3.7/site-packages/ervin/ervin.py", line 66, in run
> run_ts)
> File "/home/vguerra/ervin_env/lib/python3.7/site-packages/ervin/probe_blaster.py", line 126, in run_probe_blaster
> run_time, output_dir)
> File "/home/vguerra/ervin_env/lib/python3.7/site-packages/ervin/probe_blaster.py", line 103, in print_results
> with open(output_filepath, 'w') as result_out:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/probe_blaster/POL_ALV_AJG42161.1_Pol_[Avian_leukosis_virus_ev/J]_2020-08-10_09-45-23.tsv'
> Done
> Do you guys have any suggestions of what I could do to troubleshoot the problem?
> 
> Best,
> Vanessa

Hi,

I also get similar errors. How to fix it?

Thanks
Philge

**Comment by LeeYEAH2** [comment]
To all of the users meeting this problem, you meet this issue just because your server can't create a file with "/" in its name. Just simply modify your fasta sequnce name and problem will be solved.
